### ISSUE TITLE
Cannot create from iterable

### ISSUE THREAD

**Issue by pombredanne** [inveniosoftware/intbitset#47]
Following discussions in #43 it appears that iterables cannot be used to construct an `intbitset`:

```
>>> from intbitset import intbitset
>>> intbitset(xrange(4))
intbitset([0, 1, 2, 3])
>>> intbitset(x for x in range(4))
intbitset([])
>>> intbitset([x for x in range(4)])
intbitset([0, 1, 2, 3])
```

**Comment by pombredanne** [comment]
FWIW, this is rather minor, as it only requires otherwise to wrap in a list like I do here: https://github.com/nexB/scancode-toolkit/blob/1ff61e5858186210dd8393f7ee55c20c30168369/src/licensedcode/spans.py#L114

**Comment by bbbbbbbbba** [comment]
It seems like this is now partially resolved, but an error happens with an *empty* generator.
```
>>> from intbitset import intbitset
>>> intbitset(range(10))
intbitset([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> intbitset(range(0))
intbitset([])
>>> intbitset(i for i in range(10))
intbitset([])
>>> intbitset(i for i in range(0))
Traceback (most recent call last):
  File "intbitset.pyx", line 182, in intbitset.intbitset.__cinit__
ValueError: max() arg is an empty sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "intbitset.pyx", line 255, in intbitset.intbitset.__cinit__
  File "intbitset.pyx", line 250, in intbitset.intbitset.__cinit__
ValueError: retrieving integers from rhs is impossible: max() arg is an empty sequence
```

**Comment by bbbbbbbbba** [comment]
Actually, I just realized that a non-empty generator gives an empty `intbitset`, which is still not the right behavior. Sorry for my previous mistaken report.
